title: Kevin Villamil # your name (or website title) here
logo: "/images/img003 (2).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist, Ciudad de Méxcio, México
  <br><br>
  Mi objetivo es ___________
  <br><br>
  Tengo experiencia en Ingenieria de Datos y Machine Learning
  <br><br>
  <a href="https://www.linkedin.com/in/KevVillamil/">Entra a mi perfil de LinkedIn</a> 
  <br><br>
  <a href="/pdf/plantilla-curriculum-blanco.pdf">Mira mi Curriculum Vitae (CV) </a> 
  
theme: jekyll-theme-minimal
